name: InfuseV1
version: '$version'
main: org.turbojax.infusev1.paper.Main
api-version: '26.1.1'
authors: [TurboJax]
commands:
  infuse:
    description: Base command for Infuse
    usage: /infuse help
  drain:
    description: Drains a random positive effect from the player
    usage: /drain
    permission: infusev1.drain
permissions:
  infusev1.help:
    description: "Lets players use `/infuse help`"
    default: true
  infusev1.drain:
    description: "Lets players use `/infuse drain`"
    default: true
  infusev1.reload:
    description: "Lets players use `/infuse reload`"
  infusev1.getscore:
    description: "Lets players use `/infuse getscore`"
    default: true
  infusev1.getscore.other:
    description: "Lets players use `/infuse getscore <player>`"
  infusev1.setscore:
    description: "Lets players use `/infuse setscore`"
  infusev1.give:
    description: "Lets players use `/infuse give`"
